name: Test Deploy to AWS EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash
        
      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAXFKCTZZILK5BZSP3
          aws-secret-access-key: 0leeK/q+WS6hFNor3yLg/QGbFxaMt7DEh0P+Nb78
          aws-session-token: FwoGZXIvYXdzEND//////////wEaDPM1yw/y6wXegL+5FCLAAQnR2Xbfc+2TivpHpoWZFpBr8tqSL+yIjzbtDSMXmHWlu/wSCV7+22MCIL64PWXWUx6a3R6GPdiu+uRNKHGkeUTgLjLvRbjLqHrKCIhcQRQBK62H1ih3c3dfjFxxpBO6lqcLjRluJLak9T2fsT4twRktYEDlqLAyer5vxVilBOKGj4dRiqBczEunyRzvNmIg06p7gIPWQRw9Gv+ZG/GMk4ygwWOYilzBDoFsUJOGmX+Tt38AKSZD62KcVAnhl4auGijR8pT2BTIt44IWEJ3ul6+H3780zB56+GLzMGJWsGPmyleI538dg8PvoJWA0J+xrwatDzqi
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp --region us-east-1 ./$GITHUB_SHA.zip s3://airbnb11-bucket/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name deploy-app --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name airbnb11 --s3-location bucket=airbnb11-bucket,bundleType=zip,key=$GITHUB_SHA.zip
